# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/Glaciens/ZYBO/Galaga/Galaga.cache/wt [current_project]
set_property parent.project_path D:/Users/Glaciens/ZYBO/Galaga/Galaga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/Users/Glaciens/ZYBO/ip_repo/myip2_1.0
  d:/Users/Glaciens/ZYBO/ip_repo/myipGalaga_1.0
} [current_project]
set_property ip_output_repo d:/Users/Glaciens/ZYBO/Galaga/Galaga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/ClkTree.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/RGB_Converter.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/VGA1024.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/background.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/bee.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/boss.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/butterfly.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/digit.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/ebene.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/enemy_movement.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/enemyshoot.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/letter.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/level.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/life.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/menu.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/player.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/score.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/ship.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/shoot.v
  D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/sources_1/new/Galaga.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/constrs_1/imports/Master Datei/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Users/Glaciens/ZYBO/Galaga/Galaga.srcs/constrs_1/imports/Master Datei/ZYBO_Master.xdc}}]


synth_design -top Galaga -part xc7z010clg400-1


write_checkpoint -force -noxdef Galaga.dcp

catch { report_utilization -file Galaga_utilization_synth.rpt -pb Galaga_utilization_synth.pb }
